### ISSUE TITLE
Issue present on iPhone10,4 on iOS 13.5

### ISSUE THREAD

**Issue by Saleh56** [Sileo/DeveloperDocumentation#20]
Issue present on iPhone10,4 on iOS 13.5
Sileo version 1.8.5

The app crashes if an attempt to press the search button on the bottom right before the initial apt update/refresh sources, but is not present after or during later refreshes.

_Originally posted by @ItHertzSoGood in https://github.com/Sileo/Sileo/issues/59_

**Comment by Shugabuga** [comment]
This repo is for documentation _only_. Please keep Sileo (as in, the app itself) bug discussion in the appropriate repo.
