### ISSUE TITLE
Actionmenu error

### ISSUE THREAD

**Issue by paparaha4** [Sileo/DeveloperDocumentation#22]
![image](https://user-images.githubusercontent.com/61214392/100595345-5fe01d00-332d-11eb-9c3e-9c28327a4027.png)

**Comment by Shugabuga** [comment]
This repo is for the developer documentation for Sileo, not for technical support. Closing for being unrelated.

Regardless, please try installing the package in another package manager (such as Zebra or Installer 5) and see if you get the same error. If you do, contact the developer of the package you are installing. If it's limited to Sileo, please use https://github.com/Sileo/Sileo/ to report the bug (or do it on the Sileo Discord server, if you're on it).
